### PR TITLE
version should be 2.0.0, not '2.0.0'

### PR DESCRIPTION
**Pull request by LGLO**
Fixes:
```
[error] failed to resolve Scalafmt version '2.0.0': /home/lglo/projects/interop-scalaz/.scalafmt.conf
```

### CODE REVIEW

**Comment by mijicd** [comment]
This is a very strange behavior. I don't have problems with either approach, but it looks like there's some funky artifacts issue here.

**Comment by LGLO** [comment]
This error disappeared after I've changed to `2.0.0`. When I changed back to `"2.0.0"` it didn't happen. I was trying to locate it somewhere in my cache and remove but I couldn't find it.
[Documentation of scalafmt](https://scalameta.org/scalafmt/docs/configuration.html) presents `"2.0.0"` but in [their own code](https://github.com/scalameta/scalafmt/blob/master/.scalafmt.conf#L1) they use: `version=2.0.0-RC5`.
Please let me leave this issue open for some time until I learn which one is the correct way.

**Comment by mijicd** [comment]
Personally, I always use it with quotes :). Ok, let's leave this open until you find the underlying cause. I'll cut another release as we've bumped ZIO version.

**Comment by kaishh** [comment]
If the issue persists, it's most likely a bug in scalafmt's custom config parsing lib https://github.com/olafurpg/metaconfig/ , not sure we should pay too much attention to that...

**Pull request closed without merging**
